export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const BATCH_DELETE_EMPLOYEES = "BATCH_DELETE_EMPLOYEES";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
